language: python

matrix:
  include:
  - os: linux
    dist: trusty
    python: "3.5"
  - os: linux
    dist: trusty
    python: "3.6"
  - os: linux
    dist: xenial
    python: "3.7"

install:
  - pip install --upgrade flask flask-restful requests pytest pytest-cov pylint
  - pip install --editable .

before_script:
  - export LOOSESERVERPATH=$(pwd)/looseserver
  - cd tests

script:
  - py.test --cov $LOOSESERVERPATH --cov-report term-missing --cov-branch test_looseserver
