language: python
python:
  - "3.5"

install:
  - pip install flask flask-restful requests pytest pytest-cov pylint
  - pip install --editable .

before_script:
  - export LOOSESERVERPATH=$(pwd)/looseserver
  - cd tests

script:
  - py.test --cov $LOOSESERVERPATH --cov-report term-missing --cov-branch test_looseserver
